language: node_js
node_js:
- '0.10'
env:
  global:
    secure: sdI6uYotExkrZIfBQFkHdmoGe8tnLhgrk7lFpxUdEFYZVefuRMTs2RnUb+ZvBjJQaE2hTBZjL3QLxjZFPVFR/2RBDJmy8jlRMCLtoQGaSYUS1R4Y8z3kTDOQ2gZ4LHZb4261dWNcInRHnOrU+d29lp04EhY6gllMo58I21RQ/eE=
